pipeline {
    agent any

    environment {
        IMAGE_TAG = "jenkins-${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verify Project') {
            steps {
                sh 'pwd'
                sh 'ls -la'
                sh 'ls -la docker/hello-api'
                sh 'ls -la docker/bye-api'
            }
        }

        stage('Build Docker Images') {
            steps {
                sh 'docker build -t vsdpsingh/hello-api:${IMAGE_TAG} docker/hello-api'
                sh 'docker build -t vsdpsingh/bye-api:${IMAGE_TAG} docker/bye-api'
            }
        }

        stage('Docker Hub Login') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKERHUB_USERNAME',
                        passwordVariable: 'DOCKERHUB_TOKEN'
                    )
                ]) {
                    sh '''
                        echo "$DOCKERHUB_TOKEN" | docker login \
                            --username "$DOCKERHUB_USERNAME" \
                            --password-stdin
                    '''
                }
            }
        }

        stage('Push Docker Images') {
            steps {
                sh 'docker push vsdpsingh/hello-api:${IMAGE_TAG}'
                sh 'docker push vsdpsingh/bye-api:${IMAGE_TAG}'
            }
        }
    }

}